targets:
  swagger_to_flutter:swagger_to_flutter:
    builders:
      swagger_to_flutter:
        enabled: True
builders:
  swagger_to_flutter:
    import: 'package:swagger_to_flutter/sagger_to_flutter.dart'
    builder_factories: ['swaggerCodeBuilder']
    build_extensions:
      '$lib$': ['.swagger.dart', '.models.dart', '.converter.dart']
    build_to: source
    auto_apply: dependents
    runs_before: ['chopper_generator']